### ISSUE TITLE
the splash windows are too small

### ISSUE THREAD

**Issue by notnorandxnor** [2called-chaos/gtav-online-ahk#12]
could be because I'm running on a larger screen, I scaled dimensions by about 3 and it looks better now

**Comment by 2called-chaos** [comment]
What did you do to fix it? Just increased the splash text window sizes? Does that not leave the text as is? Or was the text ok but cut off?

**Comment by notnorandxnor** [comment]
I created a pull request, see #14 

It has to do with Windows Display Settings, on larger screen it suggests a scaling factor for text, for me it was 300%, so I set a scalar of 3.  See screenshot below...

![image](https://user-images.githubusercontent.com/98861856/152903912-9787290a-e7e1-49b4-a4f4-55bfacdcaa57.png)

**Comment by 2called-chaos** [comment]
Resolved by #14
