### ISSUE TITLE
windows key (#) doesn't work for me

### ISSUE THREAD

**Issue by notnorandxnor** [2called-chaos/gtav-online-ahk#13]
This may just be a noob issue, but I can't figure out how to use the default snacks key (ie., windows key), it does nothing for me in game, though works outside of the game, as a windows key (bringing up windows menu stuff)

**Comment by 2called-chaos** [comment]
It was meant to (and works like) the literal hashtag (#) which is next to the enter key on my layout but I give you that it also is the modifier symbol for the windows key. The thing is that

> Unlike Ctrl/Alt/Shift, there is no generic/neutral "Win" key because the OS does not support it.

So for it to mean windows key it has to be `>#` or `<#` specifically.

https://www.autohotkey.com/docs/KeyList.htm

**Comment by notnorandxnor** [comment]
ohhh ok, thanks!
