### ISSUE TITLE
Eat snacks issue

### ISSUE THREAD

**Issue by IceLancerSR** [2called-chaos/gtav-online-ahk#18]
Hello, i tried both old ahk from 2015 and this one, both behave the same way. Once i activate assigned key all it does is opens M(menu) scrolls down twice, to GPS and presses enter on it.
It doesnt even reach snacks menu. 
Same thing is happening to Armor. Press F1 and it does identical thing above.

**Comment by IceLancerSR** [comment]
Ok im getting somewhere, had to force manual inventory location to true and set inventory slot to 5, now its working (partially)
it eats snacks , menu closes , but my health isnt being regenerate while snacks is consumed.
Manually doing same thing,  health regenerates?

**Comment by 2called-chaos** [comment]
Yeah you need to go into cover for snacks. Or if you time it right, it works in certain animations (getting in/out of a vehicle I think) and jumping/climbing up. Might even work in ADS (aim down sight) not sure.

Are you CEO/MC? This shifts the interaction menu by one and requires to enable CEO/VIP mode (`ToggleVIPKey` you can also default to that by setting `IsVIPActivated` to true). This has no effect when you use manual location though. But then you have to change it manually when you are VIP vs when you are not.

Just note that inside Cayo Perico finale (as host) there is another menu shift (CPHMode) and when you are inside certain buildings (your own to invite people, car meet, etc)

Btw: Its called VIP mode for legacy reasons when this was a thing and there was no CEO/MC

**Comment by IceLancerSR** [comment]
Ok, got it. Thanks for explanation.
