### ISSUE TITLE
ArrayChatSnippets: typeout not working smoothly

### ISSUE THREAD

**Issue by ghost** [2called-chaos/gtav-online-ahk#3]
Good day, 

I have the problem that the typeout of ArrayChatSnippets is not working smoothly.
 Feels like my game is not tabbing in fast enough, that my player begins to jump or punch and then types half of the text into the chat window.
I hope that you understand, what I tried to explain and hope we will find a solution soon.

**Comment by 2called-chaos** [comment]
Hey there,

Did you read the part "chat should already be open"? It would be somewhat trivial to also press the chat key before but this way I can decide if I want to type it in all or just organization chat. Also do you happen to play in proper fullscreen as opposed to borderless window?
