### ISSUE TITLE
Issue in the new heist

### ISSUE THREAD

**Issue by caddish** [2called-chaos/gtav-online-ahk#5]
The health and snack are not working in the final heist of cayo perico because there is an additional menu at the top

**Comment by 2called-chaos** [comment]
I haven't played the new update yet but I will take a look. I suppose the easiest way is a switch like the CEO toggle? Any objections? I personally already struggle with finding enough keys to bind everything :)

Btw if it's at the top, may the CEO toggle maybe already work? It currently just adds an additional `down` on every top-level menu action that initially sends a `down` (as opposed to `up` wrapping around to the bottom of the menu) to skip the CEO entry at the top.

I'm not sure if it's feasible (or reasonably fast) to do some sort of pixel-check to see which menu configuration is active. I thought about this for the CEO menu before. My main concern is the potentially varying positioning (my 16:10 resolution for example probably aligns the menu differently, windowed mode, etc.) and I'm not entirely sure how AHK's pixel querying works (as to trigger any sort of anti-cheat or anti-tampering measures).

**Comment by caddish** [comment]
I think it could be a third state to the VIP toggle

0 = VIP off
1 = VIP on
2 = Cayo Perico Heist Final

Or another toggle entirely

Yeah the UI positioning varies, I play in ultra wide and there is an option
to push the UI toward the center so even more unpredictable

Btw cheers on this script, couldn't play without it :P

**Comment by 2called-chaos** [comment]
> I think it could be a third state to the VIP toggle 0 = VIP off 1 = VIP on 2 = Cayo Perico Heist Final

I edited my comment (you probably didn't see that in the email notification):  On second thought shouldn't the CEO toggle already do the job? All it does is sending an additional `down` to skip the CEO entry or are you CEO too in the heist (meaning having a CEO menu)?

> Yeah the UI positioning varies, I play in ultra wide and there is an option to push the UI toward the center

Oh yeah, totally forgot about the safe-zone. Probably not worth following that idea then, would require complicated configuration like measuring out an exact pixel or something.

> Btw cheers on this script, couldn't play without it :P

Thanks :) Same here. Especially the kill-switch is most useful. But I probably wouldn't have done it without [the base work of twentyafterfour](https://www.reddit.com/r/GrandTheftAutoV_PC/comments/34vdrt/i_made_some_useful_macros_for_heistsgeneral/) who figured out a lot of stuff like delays, etc.

**Comment by caddish** [comment]
Yes during the heist you are both CEO + one additional entry at the top
(reinforcement)

**Comment by caddish** [comment]
So basically one additional {down} is needed.
Currently I added one outside the IsVip loop so for me
0=vip
1=vip + reinforcement

**Comment by 2called-chaos** [comment]
So I added a new toggle and the option to make the VIP toggle 3 way (both off/VIP on/CPH on). I couldn't really test it in game because I yet have to update :)

Only thing that won't work right now is to call a CEO buzzard while CPH is on or required. Can you call a buzzard in the heist?

FYI: I also just added support for an optional config file so that updating the main script is easier as your config is separated, see https://github.com/2called-chaos/gtav-online-ahk#config

**Comment by caddish** [comment]
Great
