### ISSUE TITLE
First Person View Only when doing CPHeist?

### ISSUE THREAD

**Issue by TeeJay55** [2called-chaos/gtav-online-ahk#6]
Hello,
Using this script, when doing the CP Heist i cannot switch the VIEW anymore...i'm always in First Person View - which i do NOT prefer.
Is there something i can do about that?
Thanks in advance!

**Comment by TeeJay55** [comment]
Sorry, i should have read what was said... seems to work when in borderless window.
Tnaks anyway!

**Comment by TeeJay55** [comment]
Works nicely!

**Comment by 2called-chaos** [comment]
Glad you fixed it :)
