### ISSUE TITLE
Plz update this thing

### ISSUE THREAD

**Issue by bmw-99** [2called-chaos/gtav-online-ahk#8]
Plz update this thing

**Comment by 2called-chaos** [comment]
I'm currently addicted to another game but the tuners update might bring me back :)

What's broken?

**Comment by Tmp341** [comment]
Probably becoming CEO etc. Some lines added in Interaction menu for example.

**Comment by 2called-chaos** [comment]
Ah I see. Maybe I can take a look this week :) Also have to update the game first

**Comment by Acromatic** [comment]
it's the tuners update, it adds some lines, additions in the phone etc.... btw I used this for awhile, now I have a red dead version, needs some updates and stuff but it works as is and uses your update method, by tomorrow it will update properly and can be used

**Comment by Acromatic** [comment]
I'll write this for you given a week or two, I intend to fork this and continue writing on it, I play both games

**Comment by QUAKEULUS** [comment]
a lot is broken

**Comment by QUAKEULUS** [comment]
i fixed the basics
